[tool.poetry]
name = "chroma-ai"
version = "0.1.0"
description = "Chroma AI Project"
authors = ["Artem Mitin <mitin1005@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
fastapi = "0.115.12"
loguru = "0.7.3"
uvicorn = "0.34.0"
websockets = "15.0.1"
pydantic-settings = "2.8.1"
pydantic = "2.11.1"
pyjwt = "2.10.1"
ultralytics = {version = "8.3.101", extras = ["dill"]}
numpy = "2.1.1"
opencv-python = "4.11.0.86"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
